In [1]:
# Importing modules
import pandas as pd

In [2]:
# Read CSV
orig_data_df = pd.read_csv('Data\AviationData_Only_US.csv', engine='python')

# Display DF
orig_data_df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,State,Country,Latitude,Longitude,Airport.Code,...,Purpose.of.Flight,Air.Carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.Phase.of.Flight,Report.Status,Publication.Date
0,20200509X11853,Accident,CEN20LA173,5/9/2020,Haskell,OK,United States,35.864167,-95.655556,2K9,...,Personal,NaN,NaN,1.0,NaN,NaN,VMC,DESCENT,Preliminary,14-05-2020
1,20200508X55730,Accident,CEN20CA176,5/8/2020,San Antonio,TX,United States,29.723334,-98.694444,5C1,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,14-05-2020
2,20200507X60215,Accident,CEN20CA174,5/6/2020,Gonazales,TX,United States,29.529167,-97.464167,T20,...,Personal,NaN,NaN,NaN,NaN,2.0,VMC,NaN,Preliminary,14-05-2020
3,20200509X85739,Accident,ERA20CA175,5/3/2020,Shirley,NY,United States,40.828056,-72.865556,HWV,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary,15-05-2020
4,20200504X54503,Incident,ENG20IA031,5/3/2020,Clewiston,FL,United States,26.735000,-81.051111,NaN,...,Personal,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary,12/5/2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79218,20041105X01764,Accident,CHI79FA064,8/2/1979,Canton,OH,United States,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,NaN,VMC,APPROACH,Probable Cause,16-04-1980
79219,20001218X45448,Accident,LAX96LA321,6/19/1977,EUREKA,CA,United States,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause,12/9/2000
79220,20061025X01555,Accident,NYC07LA005,8/30/1974,Saltville,VA,United States,36.922223,-81.878056,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,CRUISE,Probable Cause,26-02-2007
79221,20001218X45447,Accident,LAX94LA336,7/19/1962,BRIDGEPORT,CA,United States,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,UNKNOWN,Probable Cause,19-09-1996
79222,20001218X45444,Accident,SEA87LA080,10/24/1948,MOOSE CREEK,ID,United States,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,CRUISE,Probable Cause,NaN

In [3]:
# List the columns in the DF
orig_data_df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'State', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.Damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.Flight', 'Air.Carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.Phase.of.Flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [4]:
# Dropping the columns which are not necessary
orig_data_df.drop(['Registration.Number', 'Amateur.Built', 
                   'FAR.Description', 'Publication.Date', 'Schedule',
                   'Air.Carrier', 'Publication.Date'],
                   axis = 1, inplace = True)

In [5]:
# Display DF
orig_data_df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,State,Country,Latitude,Longitude,Airport.Code,...,Number.of.Engines,Engine.Type,Purpose.of.Flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.Phase.of.Flight,Report.Status
0,20200509X11853,Accident,CEN20LA173,5/9/2020,Haskell,OK,United States,35.864167,-95.655556,2K9,...,NaN,NaN,Personal,NaN,1.0,NaN,NaN,VMC,DESCENT,Preliminary
1,20200508X55730,Accident,CEN20CA176,5/8/2020,San Antonio,TX,United States,29.723334,-98.694444,5C1,...,NaN,NaN,Personal,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary
2,20200507X60215,Accident,CEN20CA174,5/6/2020,Gonazales,TX,United States,29.529167,-97.464167,T20,...,1.0,NaN,Personal,NaN,NaN,NaN,2.0,VMC,NaN,Preliminary
3,20200509X85739,Accident,ERA20CA175,5/3/2020,Shirley,NY,United States,40.828056,-72.865556,HWV,...,1.0,NaN,Personal,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary
4,20200504X54503,Incident,ENG20IA031,5/3/2020,Clewiston,FL,United States,26.735000,-81.051111,NaN,...,1.0,Turbo Shaft,Personal,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79218,20041105X01764,Accident,CHI79FA064,8/2/1979,Canton,OH,United States,NaN,NaN,NaN,...,NaN,NaN,Personal,1.0,2.0,NaN,NaN,VMC,APPROACH,Probable Cause
79219,20001218X45448,Accident,LAX96LA321,6/19/1977,EUREKA,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause
79220,20061025X01555,Accident,NYC07LA005,8/30/1974,Saltville,VA,United States,36.922223,-81.878056,NaN,...,1.0,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,CRUISE,Probable Cause
79221,20001218X45447,Accident,LAX94LA336,7/19/1962,BRIDGEPORT,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,UNKNOWN,Probable Cause
79222,20001218X45444,Accident,SEA87LA080,10/24/1948,MOOSE CREEK,ID,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,CRUISE,Probable Cause

In [6]:
# Rename columns to replace . with _ in the column name
orig_data_df.rename(columns={'Event.Id' : 'Event_Id', 
                             'Investigation.Type' : 'Investigation_Type',
                             'Accident.Number' : 'Accident_Number',
                             'Event.Date' : 'Event_Date',
                             'Airport.Code' : 'Airport_Code',
                             'Airport.Name' : 'Airport_Name',
                             'Aircraft.Category' : 'Aircraft_Category',
                             'Injury.Severity' : 'Injury_Severity',
                             'Aircraft.Damage' : 'Aircraft_Damage',
                             'Number.of.Engines' : 'Number_of_Engines',
                             'Engine.Type' : 'Engine_Type',
                             'Purpose.of.Flight' : 'Purpose_of_Flight',
                             'Total.Fatal.Injuries' : 'Total_Fatal_Injuries',
                             'Total.Serious.Injuries' : 'Total_Serious_Injuries',
                             'Total.Minor.Injuries' : 'Total_Minor_Injuries',
                             'Total.Uninjured' : 'Total_Uninjured',
                             'Weather.Condition' : 'Weather_Condition',
                             'Broad.Phase.of.Flight' : 'Broad_Phase_of_Flight',
                             'Report.Status' : 'Report_Status'
                            }, inplace = True)

# Display DF
orig_data_df

,Event_Id,Investigation_Type,Accident_Number,Event_Date,Location,State,Country,Latitude,Longitude,Airport_Code,...,Number_of_Engines,Engine_Type,Purpose_of_Flight,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Weather_Condition,Broad_Phase_of_Flight,Report_Status
0,20200509X11853,Accident,CEN20LA173,5/9/2020,Haskell,OK,United States,35.864167,-95.655556,2K9,...,NaN,NaN,Personal,NaN,1.0,NaN,NaN,VMC,DESCENT,Preliminary
1,20200508X55730,Accident,CEN20CA176,5/8/2020,San Antonio,TX,United States,29.723334,-98.694444,5C1,...,NaN,NaN,Personal,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary
2,20200507X60215,Accident,CEN20CA174,5/6/2020,Gonazales,TX,United States,29.529167,-97.464167,T20,...,1.0,NaN,Personal,NaN,NaN,NaN,2.0,VMC,NaN,Preliminary
3,20200509X85739,Accident,ERA20CA175,5/3/2020,Shirley,NY,United States,40.828056,-72.865556,HWV,...,1.0,NaN,Personal,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary
4,20200504X54503,Incident,ENG20IA031,5/3/2020,Clewiston,FL,United States,26.735000,-81.051111,NaN,...,1.0,Turbo Shaft,Personal,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79218,20041105X01764,Accident,CHI79FA064,8/2/1979,Canton,OH,United States,NaN,NaN,NaN,...,NaN,NaN,Personal,1.0,2.0,NaN,NaN,VMC,APPROACH,Probable Cause
79219,20001218X45448,Accident,LAX96LA321,6/19/1977,EUREKA,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause
79220,20061025X01555,Accident,NYC07LA005,8/30/1974,Saltville,VA,United States,36.922223,-81.878056,NaN,...,1.0,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,CRUISE,Probable Cause
79221,20001218X45447,Accident,LAX94LA336,7/19/1962,BRIDGEPORT,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,UNKNOWN,Probable Cause
79222,20001218X45444,Accident,SEA87LA080,10/24/1948,MOOSE CREEK,ID,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,CRUISE,Probable Cause

In [7]:
# Get the unique list of values from injury_severity column
orig_data_df['Injury_Severity'].unique()

array(['Non-Fatal', 'Unavailable', 'Incident', 'Fatal(1)', 'Fatal(2)',
       'Fatal(3)', 'Fatal(4)', 'Fatal(5)', 'Fatal(9)', 'Fatal(7)',
       'Fatal(10)', 'Fatal(11)', 'Fatal(6)', 'Fatal(16)', 'Fatal(14)',
       'Fatal(50)', 'Fatal(8)', 'Fatal(49)', 'Fatal(20)', 'Fatal(13)',
       'Fatal(21)', 'Fatal(265)', 'Fatal(44)', 'Fatal(64)', 'Fatal(65)',
       'Fatal(92)', 'Fatal(18)', 'Fatal(19)', 'Fatal(88)', 'Fatal(228)',
       'Fatal(29)', 'Fatal(230)', 'Fatal(110)', 'Fatal(12)', 'Fatal(15)',
       'Fatal(68)', 'Fatal(132)', 'Fatal(37)', 'Fatal(27)', 'Fatal(23)',
       'Fatal(25)', 'Fatal(34)', 'Fatal(73)', 'Fatal(111)', 'Fatal(43)',
       'Fatal(28)', 'Fatal(156)', 'Fatal(82)', 'Fatal(17)', 'Fatal(31)',
       'Fatal(135)', 'Fatal(70)', 'Fatal(153)', 'Fatal(78)'], dtype=object)

In [8]:
# As the Fatal value in Injury_Severity column has the number of fatal injury 
# count which we already have in another column.
# Replacing all these values with Fatal

orig_data_df['Injury_Severity'] = orig_data_df['Injury_Severity'].replace( ['Fatal(1)', 'Fatal(2)',
       'Fatal(3)', 'Fatal(4)', 'Fatal(5)', 'Fatal(9)', 'Fatal(7)',
       'Fatal(10)', 'Fatal(11)', 'Fatal(6)', 'Fatal(16)', 'Fatal(14)',
       'Fatal(50)', 'Fatal(8)', 'Fatal(49)', 'Fatal(20)', 'Fatal(13)',
       'Fatal(21)', 'Fatal(265)', 'Fatal(44)', 'Fatal(64)', 'Fatal(65)',
       'Fatal(92)', 'Fatal(18)', 'Fatal(19)', 'Fatal(88)', 'Fatal(228)',
       'Fatal(29)', 'Fatal(230)', 'Fatal(110)', 'Fatal(12)', 'Fatal(15)',
       'Fatal(68)', 'Fatal(132)', 'Fatal(37)', 'Fatal(27)', 'Fatal(23)',
       'Fatal(25)', 'Fatal(34)', 'Fatal(73)', 'Fatal(111)', 'Fatal(43)',
       'Fatal(28)', 'Fatal(156)', 'Fatal(82)', 'Fatal(17)', 'Fatal(31)',
       'Fatal(135)', 'Fatal(70)', 'Fatal(153)', 'Fatal(78)'], 'Fatal')

In [9]:
# Verifying if all the values are replaced.
orig_data_df['Injury_Severity'].unique()

array(['Non-Fatal', 'Unavailable', 'Incident', 'Fatal'], dtype=object)

In [10]:
# Copyting data to another df to get the perfect data set
perfect_data_df = orig_data_df.copy()

# Displat new DF
perfect_data_df

,Event_Id,Investigation_Type,Accident_Number,Event_Date,Location,State,Country,Latitude,Longitude,Airport_Code,...,Number_of_Engines,Engine_Type,Purpose_of_Flight,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Weather_Condition,Broad_Phase_of_Flight,Report_Status
0,20200509X11853,Accident,CEN20LA173,5/9/2020,Haskell,OK,United States,35.864167,-95.655556,2K9,...,NaN,NaN,Personal,NaN,1.0,NaN,NaN,VMC,DESCENT,Preliminary
1,20200508X55730,Accident,CEN20CA176,5/8/2020,San Antonio,TX,United States,29.723334,-98.694444,5C1,...,NaN,NaN,Personal,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary
2,20200507X60215,Accident,CEN20CA174,5/6/2020,Gonazales,TX,United States,29.529167,-97.464167,T20,...,1.0,NaN,Personal,NaN,NaN,NaN,2.0,VMC,NaN,Preliminary
3,20200509X85739,Accident,ERA20CA175,5/3/2020,Shirley,NY,United States,40.828056,-72.865556,HWV,...,1.0,NaN,Personal,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary
4,20200504X54503,Incident,ENG20IA031,5/3/2020,Clewiston,FL,United States,26.735000,-81.051111,NaN,...,1.0,Turbo Shaft,Personal,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79218,20041105X01764,Accident,CHI79FA064,8/2/1979,Canton,OH,United States,NaN,NaN,NaN,...,NaN,NaN,Personal,1.0,2.0,NaN,NaN,VMC,APPROACH,Probable Cause
79219,20001218X45448,Accident,LAX96LA321,6/19/1977,EUREKA,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause
79220,20061025X01555,Accident,NYC07LA005,8/30/1974,Saltville,VA,United States,36.922223,-81.878056,NaN,...,1.0,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,CRUISE,Probable Cause
79221,20001218X45447,Accident,LAX94LA336,7/19/1962,BRIDGEPORT,CA,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,UNKNOWN,Probable Cause
79222,20001218X45444,Accident,SEA87LA080,10/24/1948,MOOSE CREEK,ID,United States,NaN,NaN,NaN,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,CRUISE,Probable Cause

In [11]:
# Check for missing values in new DF
perfect_data_df.count()

Event_Id                  79223
Investigation_Type        79218
Accident_Number           79223
Event_Date                79223
Location                  79193
State                     79193
Country                   79223
Latitude                  28823
Longitude                 28813
Airport_Code              47098
Airport_Name              49714
Injury_Severity           79223
Aircraft_Damage           77284
Aircraft_Category         24982
Make                      79200
Model                     79184
Number_of_Engines         77437
Engine_Type               77916
Purpose_of_Flight         76879
Total_Fatal_Injuries      53871
Total_Serious_Injuries    52624
Total_Minor_Injuries      54060
Total_Uninjured           67484
Weather_Condition         78809
Broad_Phase_of_Flight     76218
Report_Status             79223
dtype: int64

In [12]:
# Drop all rows which includes NaN values
perfect_data_df = perfect_data_df.dropna()

In [13]:
# Verifyng count after dropping all NaN
perfect_data_df.count()

Event_Id                  123
Investigation_Type        123
Accident_Number           123
Event_Date                123
Location                  123
State                     123
Country                   123
Latitude                  123
Longitude                 123
Airport_Code              123
Airport_Name              123
Injury_Severity           123
Aircraft_Damage           123
Aircraft_Category         123
Make                      123
Model                     123
Number_of_Engines         123
Engine_Type               123
Purpose_of_Flight         123
Total_Fatal_Injuries      123
Total_Serious_Injuries    123
Total_Minor_Injuries      123
Total_Uninjured           123
Weather_Condition         123
Broad_Phase_of_Flight     123
Report_Status             123
dtype: int64

In [14]:
# Save clean file after cleanup
perfect_data_df.to_csv("Data\Perfect_AviationData.csv", index=False, header=True)

In [15]:
# Now in Original DF replace empty string values with "Unknown" 
orig_data_df[['Investigation_Type', 'Location', 'State', 'Airport_Code',
                'Airport_Name', 'Aircraft_Damage', 'Aircraft_Category', 'Make',
                'Model', 'Engine_Type', 'Purpose_of_Flight', 'Weather_Condition',
                'Broad_Phase_of_Flight', 'Report_Status'
              ]] = orig_data_df[['Investigation_Type', 'Location', 'State', 'Airport_Code',
                'Airport_Name', 'Aircraft_Damage', 'Aircraft_Category', 'Make',
                'Model', 'Engine_Type', 'Purpose_of_Flight', 'Weather_Condition',
                'Broad_Phase_of_Flight', 'Report_Status'
              ]].fillna('Unknown')

In [16]:
# Verify count
orig_data_df.count()

Event_Id                  79223
Investigation_Type        79223
Accident_Number           79223
Event_Date                79223
Location                  79223
State                     79223
Country                   79223
Latitude                  28823
Longitude                 28813
Airport_Code              79223
Airport_Name              79223
Injury_Severity           79223
Aircraft_Damage           79223
Aircraft_Category         79223
Make                      79223
Model                     79223
Number_of_Engines         77437
Engine_Type               79223
Purpose_of_Flight         79223
Total_Fatal_Injuries      53871
Total_Serious_Injuries    52624
Total_Minor_Injuries      54060
Total_Uninjured           67484
Weather_Condition         79223
Broad_Phase_of_Flight     79223
Report_Status             79223
dtype: int64

In [17]:
# In Original DF replace empty numeric values with "0" except for columns for lat & long
orig_data_df[[ 'Injury_Severity', 'Number_of_Engines', 'Total_Fatal_Injuries', 
               'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured'
              ]] = orig_data_df[[ 'Injury_Severity', 'Number_of_Engines', 'Total_Fatal_Injuries', 
               'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured'
              ]].fillna(0)

In [18]:
# Verify count again
orig_data_df.count()

Event_Id                  79223
Investigation_Type        79223
Accident_Number           79223
Event_Date                79223
Location                  79223
State                     79223
Country                   79223
Latitude                  28823
Longitude                 28813
Airport_Code              79223
Airport_Name              79223
Injury_Severity           79223
Aircraft_Damage           79223
Aircraft_Category         79223
Make                      79223
Model                     79223
Number_of_Engines         79223
Engine_Type               79223
Purpose_of_Flight         79223
Total_Fatal_Injuries      79223
Total_Serious_Injuries    79223
Total_Minor_Injuries      79223
Total_Uninjured           79223
Weather_Condition         79223
Broad_Phase_of_Flight     79223
Report_Status             79223
dtype: int64

In [19]:
# Drop all NaN values from DF now
orig_data_df = orig_data_df.dropna()

In [20]:
# Re-verify count to confirm if count for all column values is same
orig_data_df.count()

Event_Id                  28806
Investigation_Type        28806
Accident_Number           28806
Event_Date                28806
Location                  28806
State                     28806
Country                   28806
Latitude                  28806
Longitude                 28806
Airport_Code              28806
Airport_Name              28806
Injury_Severity           28806
Aircraft_Damage           28806
Aircraft_Category         28806
Make                      28806
Model                     28806
Number_of_Engines         28806
Engine_Type               28806
Purpose_of_Flight         28806
Total_Fatal_Injuries      28806
Total_Serious_Injuries    28806
Total_Minor_Injuries      28806
Total_Uninjured           28806
Weather_Condition         28806
Broad_Phase_of_Flight     28806
Report_Status             28806
dtype: int64

In [21]:
orig_data_df

,Event_Id,Investigation_Type,Accident_Number,Event_Date,Location,State,Country,Latitude,Longitude,Airport_Code,...,Number_of_Engines,Engine_Type,Purpose_of_Flight,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Weather_Condition,Broad_Phase_of_Flight,Report_Status
0,20200509X11853,Accident,CEN20LA173,5/9/2020,Haskell,OK,United States,35.864167,-95.655556,2K9,...,0.0,Unknown,Personal,0.0,1.0,0.0,0.0,VMC,DESCENT,Preliminary
1,20200508X55730,Accident,CEN20CA176,5/8/2020,San Antonio,TX,United States,29.723334,-98.694444,5C1,...,0.0,Unknown,Personal,0.0,0.0,0.0,0.0,Unknown,Unknown,Preliminary
2,20200507X60215,Accident,CEN20CA174,5/6/2020,Gonazales,TX,United States,29.529167,-97.464167,T20,...,1.0,Unknown,Personal,0.0,0.0,0.0,2.0,VMC,Unknown,Preliminary
3,20200509X85739,Accident,ERA20CA175,5/3/2020,Shirley,NY,United States,40.828056,-72.865556,HWV,...,1.0,Unknown,Personal,0.0,0.0,0.0,1.0,VMC,Unknown,Preliminary
4,20200504X54503,Incident,ENG20IA031,5/3/2020,Clewiston,FL,United States,26.735000,-81.051111,Unknown,...,1.0,Turbo Shaft,Personal,0.0,0.0,0.0,1.0,Unknown,Unknown,Preliminary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73067,20020904X01525,Accident,SEA83FA208,9/9/1983,Kalispell,MT,United States,48.120000,-113.887500,Unknown,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause
75590,20051208X01953,Accident,SEA83LA209,1/8/1983,Goldendale,WA,United States,46.041111,-120.849722,Unknown,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,VMC,CRUISE,Probable Cause
78636,20080417X00504,Accident,MIA08CA076,3/16/1982,Mobile,AL,United States,30.757778,-88.355555,MOB,...,1.0,Reciprocating,Unknown,1.0,0.0,0.0,0.0,IMC,LANDING,Probable Cause
79217,20170710X52551,Accident,NYC79AA106,9/17/1979,Boston,MA,United States,42.445277,-70.758333,Unknown,...,2.0,Turbo Fan,Unknown,0.0,0.0,1.0,44.0,VMC,CLIMB,Probable Cause
79220,20061025X01555,Accident,NYC07LA005,8/30/1974,Saltville,VA,United States,36.922223,-81.878056,Unknown,...,1.0,Reciprocating,Personal,3.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause

In [22]:
# Save Final DF to CSV
orig_data_df.to_csv("Data\Final_Clean_AviationData_US.csv", index=False, header=True)