In [1]:
# Import Modules
from sklearn import tree
import pandas as pd
from sklearn import preprocessing

##### Perfect Data Set

In [2]:
# Read CSV and rename column Injury_Severity
data_df = pd.read_csv('Data\Perfect_AviationData.csv') 
data_df = data_df.rename(columns = {'Injury_Severity' : 'Severity'})

# Display DF
data_df

,Event_Id,Investigation_Type,Accident_Number,Event_Date,Location,Country,Latitude,Longitude,Airport_Code,Airport_Name,...,Number_of_Engines,Engine_Type,Purpose_of_Flight,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Weather_Condition,Broad_Phase_of_Flight,Report_Status
0,20081126X30503,Accident,WPR09LA046,11/25/2008,"Monterey, CA",United States,36.586944,-121.842777,MRY,Monterey Peninsula Airport,...,1.0,Reciprocating,Personal,0.0,1.0,1.0,0.0,VMC,DESCENT,Probable Cause
1,20081024X13647,Accident,CEN09LA034,10/24/2008,"Breckenridge, TX",United States,32.718889,-98.891111,BKD,Stephens County,...,1.0,Reciprocating,Personal,0.0,2.0,0.0,0.0,VMC,GO-AROUND,Probable Cause
2,20081020X12359,Accident,CEN09LA024,10/19/2008,"Angleton, TX",United States,29.248889,-95.328056,KLBX,Brazoria County Airport,...,1.0,Reciprocating,Personal,0.0,0.0,0.0,1.0,VMC,APPROACH,Probable Cause
3,20081011X02304,Accident,WPR09LA009,10/10/2008,"Placerville, CA",United States,38.724167,-120.753333,PVF,Placerville Airport,...,1.0,Reciprocating,Personal,0.0,0.0,0.0,2.0,VMC,GO-AROUND,Probable Cause
4,20081006X90954,Accident,WPR09LA004,10/5/2008,"Sandy Valley, NV",United States,35.795000,-115.627223,3L2,Sky Ranch Airport,...,1.0,Reciprocating,Personal,1.0,0.0,0.0,0.0,VMC,MANEUVERING,Probable Cause
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,20070806X01122,Accident,NYC07LA134,6/8/2007,"Gallatin, TN",United States,36.406667,-86.358889,M33,Sumner County,...,1.0,Reciprocating,Business,0.0,2.0,2.0,0.0,VMC,DESCENT,Probable Cause
119,20070614X00729,Accident,MIA07LA102,5/27/2007,"Hayden, AL",United States,33.925278,-86.870000,NONE,Private,...,1.0,Reciprocating,Personal,1.0,0.0,0.0,0.0,VMC,LANDING,Probable Cause
120,20070624X00785,Accident,NYC07LA125,5/23/2007,"Leesburg, VA",United States,39.063611,-77.636666,JYO,Leesburg Municipal Airport,...,1.0,Reciprocating,Personal,0.0,0.0,1.0,0.0,VMC,CRUISE,Probable Cause
121,20070508X00524,Accident,LAX07FA150,5/3/2007,"Dillon, MT",United States,45.253333,-112.548889,DLN,Dillon,...,2.0,Turbo Jet,Personal,2.0,0.0,0.0,0.0,VMC,APPROACH,Probable Cause
122,20070427X00462,Accident,MIA07LA081,4/19/2007,"Welaka, FL",United States,29.658611,-81.688611,3FL0,Mount Royal Airpark,...,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,TAKEOFF,Probable Cause

In [3]:
# Define Target (Also called as Y)
target = data_df["Severity"]
target.head()

0    Non-Fatal
1    Non-Fatal
2    Non-Fatal
3    Non-Fatal
4        Fatal
Name: Severity, dtype: object

In [4]:
#  Encode Target values for Random Forest Model

## Get the unique list of Severity
unique_target = list(data_df["Severity"].unique())

# Create an encoder and fit on unique values
target_encoder = preprocessing.LabelEncoder()
target_encoder.fit(unique_target)

# Transform all target values with encoder and store as list
ecoded_target_list = list(target_encoder.transform(target))

# Create a final_target with encoded values
encoded_target_df = pd.DataFrame({"Severity" : ecoded_target_list})
final_target = encoded_target_df["Severity"]
final_target

0      2
1      2
2      2
3      2
4      0
      ..
118    2
119    0
120    2
121    0
122    0
Name: Severity, Length: 123, dtype: int64

In [5]:
# Define the input value columns(also called as X)
data = data_df[[
                'Aircraft_Damage', 'Aircraft_Category', 'Total_Fatal_Injuries',
                'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured', 'Broad_Phase_of_Flight'
                ]]

# Display data DF
data

,Aircraft_Damage,Aircraft_Category,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight
0,Substantial,Airplane,0.0,1.0,1.0,0.0,DESCENT
1,Destroyed,Airplane,0.0,2.0,0.0,0.0,GO-AROUND
2,Substantial,Airplane,0.0,0.0,0.0,1.0,APPROACH
3,Substantial,Airplane,0.0,0.0,0.0,2.0,GO-AROUND
4,Substantial,Airplane,1.0,0.0,0.0,0.0,MANEUVERING
...,...,...,...,...,...,...,...
118,Substantial,Airplane,0.0,2.0,2.0,0.0,DESCENT
119,Substantial,Helicopter,1.0,0.0,0.0,0.0,LANDING
120,Substantial,Airplane,0.0,0.0,1.0,0.0,CRUISE
121,Destroyed,Airplane,2.0,0.0,0.0,0.0,APPROACH
122,Substantial,Airplane,2.0,0.0,0.0,0.0,TAKEOFF

In [6]:
# List of column names which has string values
col_list = ['Aircraft_Damage', 'Aircraft_Category' , 'Broad_Phase_of_Flight']

# Iterate through each column in col_list and create a encoded values for that column
for col in col_list:
    # Get the list of unique values from column
    unique = list(data[col].unique())
    
    # Create a LabelEncoder
    encoder = preprocessing.LabelEncoder()
    
    # Store the encoder in unique variable depending on the column name
    if col == 'Aircraft_Damage':
        le_Aircraft_Damage = encoder
        
    elif col == 'Aircraft_Category':
        le_Aircraft_Category = encoder
        
    elif col == 'Broad_Phase_of_Flight':
        le_Broad_Phase_of_Flight = encoder
        
    # Fit the encoder on unique values 
    encoder.fit(unique)
    
    # Get the column values to list
    col_data_list = data[col].tolist()
    
    # Transform column values to encoded form
    ecoded_list = list(encoder.transform(col_data_list))
    
    # Add encoded values as new column in df
    new_col_name = col+'_Encoded'
    data[new_col_name] = ecoded_list

C:\Users\subha\Anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
# Display DF
data

,Aircraft_Damage,Aircraft_Category,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight,Aircraft_Damage_Encoded,Aircraft_Category_Encoded,Broad_Phase_of_Flight_Encoded
0,Substantial,Airplane,0.0,1.0,1.0,0.0,DESCENT,2,0,3
1,Destroyed,Airplane,0.0,2.0,0.0,0.0,GO-AROUND,0,0,4
2,Substantial,Airplane,0.0,0.0,0.0,1.0,APPROACH,2,0,0
3,Substantial,Airplane,0.0,0.0,0.0,2.0,GO-AROUND,2,0,4
4,Substantial,Airplane,1.0,0.0,0.0,0.0,MANEUVERING,2,0,6
...,...,...,...,...,...,...,...,...,...,...
118,Substantial,Airplane,0.0,2.0,2.0,0.0,DESCENT,2,0,3
119,Substantial,Helicopter,1.0,0.0,0.0,0.0,LANDING,2,2,5
120,Substantial,Airplane,0.0,0.0,1.0,0.0,CRUISE,2,0,2
121,Destroyed,Airplane,2.0,0.0,0.0,0.0,APPROACH,0,0,0
122,Substantial,Airplane,2.0,0.0,0.0,0.0,TAKEOFF,2,0,7

In [8]:
# Creating final_data df with only required(Numeric value) columns 
final_data = data[[
                   'Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded', 'Total_Fatal_Injuries',
                   'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured', 'Broad_Phase_of_Flight_Encoded'
                  ]]

# Display Final Data
final_data

,Aircraft_Damage_Encoded,Aircraft_Category_Encoded,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight_Encoded
0,2,0,0.0,1.0,1.0,0.0,3
1,0,0,0.0,2.0,0.0,0.0,4
2,2,0,0.0,0.0,0.0,1.0,0
3,2,0,0.0,0.0,0.0,2.0,4
4,2,0,1.0,0.0,0.0,0.0,6
...,...,...,...,...,...,...,...
118,2,0,0.0,2.0,2.0,0.0,3
119,2,2,1.0,0.0,0.0,0.0,5
120,2,0,0.0,0.0,1.0,0.0,2
121,0,0,2.0,0.0,0.0,0.0,0
122,2,0,2.0,0.0,0.0,0.0,7

In [9]:
# Define feature_names to get the important features
feature_names = final_data.columns

# Display feature names
feature_names

Index(['Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded',
       'Total_Fatal_Injuries', 'Total_Serious_Injuries',
       'Total_Minor_Injuries', 'Total_Uninjured',
       'Broad_Phase_of_Flight_Encoded'],
      dtype='object')

##### Logistic_Regression

In [10]:
# Perform train test split for logistic regression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(final_data, target, random_state=42)

In [11]:
# Scale data using StandardScalar
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

# Transform X values (Train & Test) with the scalar
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=10000)
classifier.fit(X_train_scaled, y_train)

print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9891304347826086
Testing Data Score: 0.9354838709677419

In [13]:
# Run Prediction in test data to get the predicted values for y(target)
y_pred = classifier.predict(X_test)
print(f"First 10 Predictions:   {y_pred[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   ['Non-Fatal' 'Non-Fatal' 'Non-Fatal' 'Non-Fatal' 'Fatal' 'Non-Fatal'
 'Fatal' 'Fatal' 'Fatal' 'Fatal']
First 10 Actual labels: ['Non-Fatal', 'Non-Fatal', 'Non-Fatal', 'Non-Fatal', 'Fatal', 'Non-Fatal', 'Fatal', 'Fatal', 'Fatal', 'Fatal']

In [14]:
# Create df with predicted and actual values
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)

   Prediction     Actual
0   Non-Fatal  Non-Fatal
1   Non-Fatal  Non-Fatal
2   Non-Fatal  Non-Fatal
3   Non-Fatal  Non-Fatal
4       Fatal      Fatal
5   Non-Fatal  Non-Fatal
6       Fatal      Fatal
7       Fatal      Fatal
8       Fatal      Fatal
9       Fatal      Fatal
10  Non-Fatal  Non-Fatal
11  Non-Fatal  Non-Fatal
12  Non-Fatal  Non-Fatal
13      Fatal      Fatal
14  Non-Fatal  Non-Fatal
15  Non-Fatal  Non-Fatal
16  Non-Fatal   Incident
17      Fatal      Fatal
18      Fatal      Fatal
19  Non-Fatal  Non-Fatal
20  Non-Fatal  Non-Fatal
21      Fatal      Fatal
22  Non-Fatal  Non-Fatal
23  Non-Fatal  Non-Fatal
24  Non-Fatal  Non-Fatal
25  Non-Fatal  Non-Fatal
26  Non-Fatal  Non-Fatal
27      Fatal      Fatal
28  Non-Fatal   Incident
29      Fatal      Fatal
30  Non-Fatal  Non-Fatal

In [15]:
# Display Confusion Matrix 

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test, y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[11  0  0]
 [ 0  0  2]
 [ 0  0 18]]
Classification Report:
              precision    recall  f1-score   support

       Fatal       1.00      1.00      1.00        11
    Incident       0.00      0.00      0.00         2
   Non-Fatal       0.90      1.00      0.95        18

    accuracy                           0.94        31
   macro avg       0.63      0.67      0.65        31
weighted avg       0.88      0.94      0.90        31

Accuracy: 0.9354838709677419

C:\Users\subha\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

##### Random Forest Regression

In [16]:
# Perform train test split for random forest regression
from sklearn.model_selection import train_test_split
X_train_random, X_test_random, y_train_random, y_test_random = train_test_split(final_data, final_target, random_state=42)

In [17]:
# Scale data using StandardScalar
from sklearn.preprocessing import StandardScaler
X_scaler_random = StandardScaler().fit(X_train_random)

# Transform X values (Train & Test) with the scalar
X_train_random_scaled = X_scaler_random.transform(X_train_random)
X_test_random_scaled = X_scaler_random.transform(X_test_random)

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_random_scaled, y_train_random)

print(f"Testing Data Score: {rf.score(X_test_random, y_test_random)}")
print(f"Training Data Score: {rf.score(X_train_random, y_train_random)}")

Testing Data Score: 0.45161290322580644
Training Data Score: 0.4673913043478261

In [19]:
#Run Prediction in test data to get the predicted values for y(target)
y_pred_random = list(rf.predict(X_test_random))
print(f"First 10 Predictions:   {y_pred_random[:10]}")
print(f"First 10 Actual labels: {y_test_random[:10].tolist()}")

First 10 Predictions:   [2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
First 10 Actual labels: [2, 2, 2, 2, 0, 2, 0, 0, 0, 0]

In [20]:
# Create df with predicted and actual values
pd.DataFrame({"Prediction": y_pred_random, "Actual": y_test_random}).reset_index(drop=True)

    Prediction  Actual
0            2       2
1            0       2
2            0       2
3            0       2
4            0       0
5            0       2
6            0       0
7            0       0
8            0       0
9            0       0
10           0       2
11           0       2
12           0       2
13           0       0
14           0       2
15           0       2
16           0       1
17           0       0
18           0       0
19           2       2
20           0       2
21           0       0
22           0       2
23           0       2
24           0       2
25           0       2
26           2       2
27           0       0
28           0       1
29           0       0
30           0       2

In [21]:
# Display Confusion Matrix 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result_random = confusion_matrix(y_test_random, y_pred_random)
print("Confusion Matrix:")
print(result_random)
result1_random = classification_report(y_test_random, y_pred_random)
print("Classification Report:",)
print (result1_random)
result2_random = accuracy_score(y_test_random, y_pred_random)
print("Accuracy:",result2_random)

Confusion Matrix:
[[11  0  0]
 [ 2  0  0]
 [15  0  3]]
Classification Report:
              precision    recall  f1-score   support

           0       0.39      1.00      0.56        11
           1       0.00      0.00      0.00         2
           2       1.00      0.17      0.29        18

    accuracy                           0.45        31
   macro avg       0.46      0.39      0.28        31
weighted avg       0.72      0.45      0.37        31

Accuracy: 0.45161290322580644

C:\Users\subha\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [22]:
# Display Feature names
print(feature_names)

Index(['Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded',
       'Total_Fatal_Injuries', 'Total_Serious_Injuries',
       'Total_Minor_Injuries', 'Total_Uninjured',
       'Broad_Phase_of_Flight_Encoded'],
      dtype='object')

In [23]:
# Get the Important features
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.574050819974588, 'Total_Fatal_Injuries'),
 (0.17749699274182676, 'Total_Uninjured'),
 (0.11027919358361905, 'Aircraft_Damage_Encoded'),
 (0.05628337268534107, 'Total_Serious_Injuries'),
 (0.0442074651149683, 'Total_Minor_Injuries'),
 (0.03542893697202935, 'Broad_Phase_of_Flight_Encoded'),
 (0.002253218927627572, 'Aircraft_Category_Encoded')]

##### Data Set with Unknowns

In [24]:
data_df = pd.read_csv('Data\Final_Clean_AviationData_US.csv') 
data_df = data_df.rename(columns = {'Injury_Severity' : 'Severity'})

data_df.head()

,Event_Id,Investigation_Type,Accident_Number,Event_Date,Location,Country,Latitude,Longitude,Airport_Code,Airport_Name,...,Number_of_Engines,Engine_Type,Purpose_of_Flight,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Weather_Condition,Broad_Phase_of_Flight,Report_Status
0,20200509X11853,Accident,CEN20LA173,5/9/2020,"Haskell, OK",United States,35.864167,-95.655556,2K9,HASKELL,...,0.0,Unknown,Personal,0.0,1.0,0.0,0.0,VMC,DESCENT,Preliminary
1,20200508X55730,Accident,CEN20CA176,5/8/2020,"San Antonio, TX",United States,29.723334,-98.694444,5C1,Unknown,...,0.0,Unknown,Personal,0.0,0.0,0.0,0.0,Unknown,Unknown,Preliminary
2,20200507X60215,Accident,CEN20CA174,5/6/2020,"Gonazales, TX",United States,29.529167,-97.464167,T20,Roger M Dreyer Memorial,...,1.0,Unknown,Personal,0.0,0.0,0.0,2.0,VMC,Unknown,Preliminary
3,20200509X85739,Accident,ERA20CA175,5/3/2020,"Shirley, NY",United States,40.828056,-72.865556,HWV,BROOKHAVEN,...,1.0,Unknown,Personal,0.0,0.0,0.0,1.0,VMC,Unknown,Preliminary
4,20200504X54503,Incident,ENG20IA031,5/3/2020,"Clewiston, FL",United States,26.735000,-81.051111,Unknown,Unknown,...,1.0,Turbo Shaft,Personal,0.0,0.0,0.0,1.0,Unknown,Unknown,Preliminary

In [25]:
# Define Target (Also called as Y)
target = data_df["Severity"]
target.head()

0      Non-Fatal
1    Unavailable
2      Non-Fatal
3      Non-Fatal
4       Incident
Name: Severity, dtype: object

In [26]:
#  Encode Target values for Random Forest Model

## Get the unique list of Severity
unique_target = list(data_df["Severity"].unique())

# Create an encoder and fit on unique values
target_encoder = preprocessing.LabelEncoder()
target_encoder.fit(unique_target)

# Transform all target values with encoder and store as list
ecoded_target_list = list(target_encoder.transform(target))

# Create a final_target with encoded values
encoded_target_df = pd.DataFrame({"Severity" : ecoded_target_list})
final_target = encoded_target_df["Severity"]
final_target

0        2
1        3
2        2
3        2
4        1
        ..
28801    0
28802    0
28803    0
28804    2
28805    0
Name: Severity, Length: 28806, dtype: int64

In [27]:
# Define the input value columns(also called as X)
data = data_df[[
                'Aircraft_Damage', 'Aircraft_Category', 'Total_Fatal_Injuries',
                'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured', 'Broad_Phase_of_Flight'
                ]]

# Display data DF
data

,Aircraft_Damage,Aircraft_Category,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight
0,Substantial,Airplane,0.0,1.0,0.0,0.0,DESCENT
1,Substantial,Airplane,0.0,0.0,0.0,0.0,Unknown
2,Substantial,Airplane,0.0,0.0,0.0,2.0,Unknown
3,Substantial,Airplane,0.0,0.0,0.0,1.0,Unknown
4,Unknown,Helicopter,0.0,0.0,0.0,1.0,Unknown
...,...,...,...,...,...,...,...
28801,Destroyed,Unknown,2.0,0.0,0.0,0.0,CRUISE
28802,Destroyed,Unknown,2.0,0.0,0.0,0.0,CRUISE
28803,Substantial,Airplane,1.0,0.0,0.0,0.0,LANDING
28804,Substantial,Airplane,0.0,0.0,1.0,44.0,CLIMB
28805,Destroyed,Unknown,3.0,0.0,0.0,0.0,CRUISE

In [28]:
# List of column names which has string values
col_list = ['Aircraft_Damage', 'Aircraft_Category', 'Broad_Phase_of_Flight']

# Iterate through each column in col_list and create a encoded values for that column
for col in col_list:
    # Get the list of unique values from column
    unique = list(data[col].unique())
    
    # Create a LabelEncoder
    encoder = preprocessing.LabelEncoder()
    
    # Store the encoder in unique variable depending on the column name
    if col == 'Aircraft_Damage':
        le_Aircraft_Damage = encoder
        
    elif col == 'Aircraft_Category':
        le_Aircraft_Category = encoder
        
    elif col == 'Broad_Phase_of_Flight':
        le_Broad_Phase_of_Flight = encoder
        
    # Fit the encoder on unique values 
    encoder.fit(unique)
    
    # Get the column values to list
    col_data_list = data[col].tolist()
    
    # Transform column values to encoded form
    ecoded_list = list(encoder.transform(col_data_list))
    
    # Add encoded values as new column in df
    new_col_name = col+'_Encoded'
    data[new_col_name] = ecoded_list

C:\Users\subha\Anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [29]:
# Display DF
data

,Aircraft_Damage,Aircraft_Category,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight,Aircraft_Damage_Encoded,Aircraft_Category_Encoded,Broad_Phase_of_Flight_Encoded
0,Substantial,Airplane,0.0,1.0,0.0,0.0,DESCENT,2,0,3
1,Substantial,Airplane,0.0,0.0,0.0,0.0,Unknown,2,0,12
2,Substantial,Airplane,0.0,0.0,0.0,2.0,Unknown,2,0,12
3,Substantial,Airplane,0.0,0.0,0.0,1.0,Unknown,2,0,12
4,Unknown,Helicopter,0.0,0.0,0.0,1.0,Unknown,3,6,12
...,...,...,...,...,...,...,...,...,...,...
28801,Destroyed,Unknown,2.0,0.0,0.0,0.0,CRUISE,0,11,2
28802,Destroyed,Unknown,2.0,0.0,0.0,0.0,CRUISE,0,11,2
28803,Substantial,Airplane,1.0,0.0,0.0,0.0,LANDING,2,0,5
28804,Substantial,Airplane,0.0,0.0,1.0,44.0,CLIMB,2,0,1
28805,Destroyed,Unknown,3.0,0.0,0.0,0.0,CRUISE,0,11,2

In [30]:
# Creating final_data df with only required(Numeric value) columns 
final_data = data[[
                   'Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded', 'Total_Fatal_Injuries',
                   'Total_Serious_Injuries', 'Total_Minor_Injuries', 'Total_Uninjured', 'Broad_Phase_of_Flight_Encoded'
                  ]]

# Display Final Data
final_data

,Aircraft_Damage_Encoded,Aircraft_Category_Encoded,Total_Fatal_Injuries,Total_Serious_Injuries,Total_Minor_Injuries,Total_Uninjured,Broad_Phase_of_Flight_Encoded
0,2,0,0.0,1.0,0.0,0.0,3
1,2,0,0.0,0.0,0.0,0.0,12
2,2,0,0.0,0.0,0.0,2.0,12
3,2,0,0.0,0.0,0.0,1.0,12
4,3,6,0.0,0.0,0.0,1.0,12
...,...,...,...,...,...,...,...
28801,0,11,2.0,0.0,0.0,0.0,2
28802,0,11,2.0,0.0,0.0,0.0,2
28803,2,0,1.0,0.0,0.0,0.0,5
28804,2,0,0.0,0.0,1.0,44.0,1
28805,0,11,3.0,0.0,0.0,0.0,2

In [31]:
# Define feature_names to get the important features
feature_names = final_data.columns

# Display feature names
feature_names

Index(['Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded',
       'Total_Fatal_Injuries', 'Total_Serious_Injuries',
       'Total_Minor_Injuries', 'Total_Uninjured',
       'Broad_Phase_of_Flight_Encoded'],
      dtype='object')

##### Logistic_Regression

In [32]:
# Perform train test split for logistic regression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(final_data, target, random_state=42)

In [33]:
# Scale data using StandardScalar
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

# Transform X values (Train & Test) with the scalar
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [34]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=10000)
classifier.fit(X_train_scaled, y_train)

print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.612479170523977
Testing Data Score: 0.6210774784782005

In [35]:
# Run Prediction in test data to get the predicted values for y(target)
y_pred = classifier.predict(X_test)
print(f"First 10 Predictions:   {y_pred[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   ['Fatal' 'Fatal' 'Unavailable' 'Unavailable' 'Non-Fatal' 'Unavailable'
 'Non-Fatal' 'Incident' 'Unavailable' 'Non-Fatal']
First 10 Actual labels: ['Fatal', 'Fatal', 'Non-Fatal', 'Fatal', 'Non-Fatal', 'Non-Fatal', 'Non-Fatal', 'Non-Fatal', 'Non-Fatal', 'Non-Fatal']

In [36]:
# Create df with predicted and actual values
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)

       Prediction     Actual
0           Fatal      Fatal
1           Fatal      Fatal
2     Unavailable  Non-Fatal
3     Unavailable      Fatal
4       Non-Fatal  Non-Fatal
...           ...        ...
7197     Incident  Non-Fatal
7198    Non-Fatal  Non-Fatal
7199  Unavailable  Non-Fatal
7200    Non-Fatal  Non-Fatal
7201    Non-Fatal  Non-Fatal

[7202 rows x 2 columns]

In [37]:
# Display Confusion Matrix 

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test, y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[1158    1    0  166]
 [   1   65   44   32]
 [   0  682 3248 1803]
 [   0    0    0    2]]
Classification Report:
              precision    recall  f1-score   support

       Fatal       1.00      0.87      0.93      1325
    Incident       0.09      0.46      0.15       142
   Non-Fatal       0.99      0.57      0.72      5733
 Unavailable       0.00      1.00      0.00         2

    accuracy                           0.62      7202
   macro avg       0.52      0.72      0.45      7202
weighted avg       0.97      0.62      0.75      7202

Accuracy: 0.6210774784782005

##### Random Forest Regression

In [38]:
# Perform train test split for random forest regression
from sklearn.model_selection import train_test_split
X_train_random, X_test_random, y_train_random, y_test_random = train_test_split(final_data, final_target, random_state=42)

In [39]:
# Scale data using StandardScalar
from sklearn.preprocessing import StandardScaler
X_scaler_random = StandardScaler().fit(X_train_random)

# Transform X values (Train & Test) with the scalar
X_train_random_scaled = X_scaler_random.transform(X_train_random)
X_test_random_scaled = X_scaler_random.transform(X_test_random)

In [40]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_random_scaled, y_train_random)

print(f"Testing Data Score: {rf.score(X_test_random, y_test_random)}")
print(f"Training Data Score: {rf.score(X_train_random, y_train_random)}")

Testing Data Score: 0.4365454040544293
Training Data Score: 0.45482318089242735

In [41]:
#Run Prediction in test data to get the predicted values for y(target)
y_pred_random = list(rf.predict(X_test_random))
print(f"First 10 Predictions:   {y_pred_random[:10]}")
print(f"First 10 Actual labels: {y_test_random[:10].tolist()}")

First 10 Predictions:   [0, 0, 2, 0, 1, 1, 2, 1, 2, 1]
First 10 Actual labels: [0, 0, 2, 0, 2, 2, 2, 2, 2, 2]

In [42]:
# Create df with predicted and actual values
pd.DataFrame({"Prediction": y_pred_random, "Actual": y_test_random}).reset_index(drop=True)

      Prediction  Actual
0              0       0
1              0       0
2              2       2
3              0       0
4              1       2
...          ...     ...
7197           1       2
7198           1       2
7199           2       2
7200           2       2
7201           2       2

[7202 rows x 2 columns]

In [43]:
# Decode actial & predicted values back to the original state

In [44]:
# Display Confusion Matrix 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result_random = confusion_matrix(y_test_random, y_pred_random)
print("Confusion Matrix:")
print(result_random)
result1_random = classification_report(y_test_random, y_pred_random)
print("Classification Report:",)
print (result1_random)
result2_random = accuracy_score(y_test_random, y_pred_random)
print("Accuracy:",result2_random)

Confusion Matrix:
[[1325    0    0    0]
 [   2   45   95    0]
 [   0 3959 1774    0]
 [   0    1    1    0]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1325
           1       0.01      0.32      0.02       142
           2       0.95      0.31      0.47      5733
           3       0.00      0.00      0.00         2

    accuracy                           0.44      7202
   macro avg       0.49      0.41      0.37      7202
weighted avg       0.94      0.44      0.56      7202

Accuracy: 0.4365454040544293

C:\Users\subha\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [45]:
# Display Feature names
print(feature_names)

Index(['Aircraft_Damage_Encoded', 'Aircraft_Category_Encoded',
       'Total_Fatal_Injuries', 'Total_Serious_Injuries',
       'Total_Minor_Injuries', 'Total_Uninjured',
       'Broad_Phase_of_Flight_Encoded'],
      dtype='object')

In [46]:
# Get the Important features
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.6031101528919665, 'Total_Fatal_Injuries'),
 (0.15742820974100644, 'Aircraft_Damage_Encoded'),
 (0.14369342816453373, 'Total_Uninjured'),
 (0.03965975917172048, 'Total_Minor_Injuries'),
 (0.03320262601943432, 'Total_Serious_Injuries'),
 (0.017556080230942236, 'Broad_Phase_of_Flight_Encoded'),
 (0.005349743780396284, 'Aircraft_Category_Encoded')]